### ISSUE TITLE
Atkinson (1994) Forward search and outlier plot

### ISSUE THREAD

**Issue by jbytecode** [jbytecode/LinRegOutliers#22]
this algorithm generates a useful outlier plot based on lms estimation which is already available in our package.

``
Atkinson, Anthony C. "Fast very robust methods for the detection of multiple outliers." Journal of the American Statistical Association 89.428 (1994): 1329-1339.
``

I plan to implement this in next few days if nobody is interested in.

**Comment by jbytecode** [comment]
okay @tantei3 , as we talked on stack channel, I am assigning you as the maintainer of this algorithm.

**Comment by jbytecode** [comment]
@tantei3 should we close this issue or should we wait until the text plot is implemented?

**Comment by tantei3** [comment]
I'll add the text plot method code in a few days, shouldn't be difficult since the residuals matrix is returned from the function.
