### ISSUE TITLE
Robust regression: A weighted least squares approach.

### ISSUE THREAD

**Issue by jbytecode** [jbytecode/LinRegOutliers#23]
I think it worths to look at the publication given below since it seeks robust estimates of regression parameters in a different way:

``
Chatterjee, Samprit, and Martin Mächler. "Robust regression: A weighted least squares approach." Communications in Statistics-Theory and Methods 26.6 (1997): 1381-1394.
``

**Comment by jbytecode** [comment]
@fmyilmaz this is more straightforward to implement when it is compared to DR derivatives. You can start with this so you can get familier with the previous methods implemented in the package.

**Comment by fmyilmaz** [comment]
Thanks! Please assign me.

**Comment by jbytecode** [comment]
okay @fmyilmaz, ask anything when you are in trouble. We are also in Julia Slack #linregoutliers channel waiting for the newcomer's questions.

**Comment by jbytecode** [comment]
@fmyilmaz any progress in this issue?

**Comment by fmyilmaz** [comment]
I am preparing the first part of my code to upload it.

**Comment by jbytecode** [comment]
@fmyilmaz  any progress with this?

**Comment by jbytecode** [comment]
The algorithm is implemented in src/cm97.jl and tested using Stackloss data. The results are checked with the ones presented in the paper. Since the implementation seems complete, I am closing this issue. 

Hope to see your contributions in the future.
