### ISSUE TITLE
Paper submission

### ISSUE THREAD

**Issue by jbytecode** [jbytecode/LinRegOutliers#24]
Hi folks, 

Firstly, thanks for all contributors and for those who are trying to implement a new functionality right now. 

We have nearly ``~20`` algorithms / papers implemented and the package is in a good state. It seems, after one or two months, the package will cover nearly %95 of the classical literature. Our long-term goal is, of course, to implement all of the pioneer algorithms on this scientific area and make them all production ready for Julia users and researches. 

Since our package is also a scientific contribution and / or a useful tool for those will construct their scientific research on the package,  it would be good to a have a citable manuscript in an academic journal. Our package perfectly fits the contextual requirements of Journal of Open Source Software (JOSS). I am planning to prepare a manuscript when the current status of our package can be considered mature (Yes, being mature is not clear but in terms of coverage and completeness, our package is in a good state). 

All valuable contributors are also natural co-authors of the paper. 

So, please make your assigned algorithm(s) ready until 2021, Jan 1st. 

Fyi, have a nice week.

**Comment by fmyilmaz** [comment]
Thanks! I am ready if there is a need for manuscript.

**Comment by jbytecode** [comment]
> Thanks! I am ready if there is a need for manuscript.

Well @fmyilmaz, first things first. Let's be a substantial contributor. After reaching a mature state, I will present the directives here.
