### ISSUE TITLE
BACON algorithm is missing

### ISSUE THREAD

**Issue by jbytecode** [jbytecode/LinRegOutliers#4]
The BACON algorithm with reference

`Billor, Nedret, Ali S. Hadi, and Paul F. Velleman. "BACON: blocked adaptive computationally efficient outlier nominators." Computational statistics & data analysis 34.3 (2000): 279-298.`

is required. Any contributor for this? volunteers will be assigned to this issue.

**Comment by SaranjeetKaur** [comment]
Hi @jbytecode, I would like to work on this issue

**Comment by jbytecode** [comment]
Okay @SaranjeetKaur welcome.

**Comment by jbytecode** [comment]
@SaranjeetKaur any opions or questions on the implementation? Please do not hesitate to ask anytime.

The BACON Algorithm has many parts including an algorithm for the outlier detection in multivariate data. Other important one is a method for linear regression. Since, matrix of independent variables are considered multivariate data in this subject, it would be good to see both of them in the package.

**Comment by SaranjeetKaur** [comment]
Sure, thanks! I will get back to this soon. Are you in the Julia slack channel?

**Comment by jbytecode** [comment]
Yes, I am.

**Comment by jbytecode** [comment]
@tantei3  is this issue resolved?

**Comment by jbytecode** [comment]
Since it is in a good state, we can consider this a finalized work and get the issue closed. We can later improve this if needed.
Dear @SaranjeetKaur, please keep in touch. Any other contributions are welcome.
