### ISSUE TITLE
Documentation - 2. Examples

### ISSUE THREAD

**Issue by salleuska** [jbytecode/LinRegOutliers#41]
As for the documentation, I think that examples could clearer if expanded a bit. I like the fact that algorithms calls follow the same structure, the function usage is pretty self-explanatory. 
However, I would suggest expanding the [example page](https://github.com/jbytecode/LinRegOutliers/blob/master/examples.md) to better reflect how the functions of the package help to perform data analysis. For example, providing few sentences describing the data, objective of the analysis and commenting the results. The example could also clarify that algorithms can provide different outputs, and that they all provide a list of outliers named `outliers` directly or contained in the `Dictionary`. 

https://github.com/openjournals/joss-reviews/issues/2892

**Comment by jbytecode** [comment]
Dear reviewer @salleuska,

[example page](https://github.com/jbytecode/LinRegOutliers/blob/master/examples.md) is updated with additional information about selected methods. An introduction section is added for better explanation of basic calling convention. The other calling convention is also mentioned. The datasets used in examples are also clarified.
