### ISSUE TITLE
Julia compat entry should be updated to 1.7 to accommodate RANSAC 

### ISSUE THREAD

**Issue by stevenaleung** [jbytecode/LinRegOutliers#43]
Using Julia 1.6.0, the RANSAC example code gave me the following error: `UndefVarError: ColumnNorm not defined`

I tracked the change to [this commit](https://github.com/JuliaLang/julia/commit/e0ecc557a24eb3338b8dc672d02c98e8b31111fa) - judging by the commit date I suspect it was introduced in version 1.7.0. I also see that the LinRegOutliers tests are passing for Julia 1.7 (the README badge is out of date)

The error was resolved after I upgraded to Julia to 1.7.1

**Comment by jbytecode** [comment]
@stevenaleung thank you for the issue. I think the latest commits solves the problem.

**Comment by stevenaleung** [comment]
Thanks for the quick turnaround!
