### ISSUE TITLE
Hadi (1994) algorithm is missing

### ISSUE THREAD

**Issue by jbytecode** [jbytecode/LinRegOutliers#5]
The algorithm with reference 

`Hadi, Ali S. "A modification of a method for the detection of outliers in multivariate samples." Journal of the Royal Statistical Society: Series B (Methodological) 56.2 (1994): 393-396.`

is required. This algorithm is modification of the Hadi (1992) algorithm which is implemented in /src/hadi1992.jl.

Implementation of this method requires small code refactors of the implemented one. 

volunteers will be assigned to this issue.

**Comment by akadal** [comment]
I can take this.

**Comment by jbytecode** [comment]
Ok assigned you to this issue, feel free to ask anything

**Comment by jbytecode** [comment]
@akadal any progress in this issue?

**Comment by akadal** [comment]
@jbytecode I am working on. It will be completed in about 2-3 weeks. Everything is ok. :)

**Comment by akadal** [comment]
I have submitted a pull request which includes Hadi'94 implementation and test. @jbytecode

**Comment by jbytecode** [comment]
Due to the implementation, I am closing this.
