### ISSUE TITLE
MVE

### ISSUE THREAD

**Issue by jbytecode** [jbytecode/LinRegOutliers#8]
the mve() function in the package results different covariance matrix when it is compared to R results using cov.mve() function in the MASS package.

Any contributions are also welcome, if there is a bug in the implemented method. However, mve & lts plot results satisfactory results.

**Comment by jbytecode** [comment]
here is a test case in R:

```
> library(MASS)
> test.data <- cbind(phones$calls, phones$year)
> test.data
       [,1] [,2]
 [1,]   4.4   50
 [2,]   4.7   51
 [3,]   4.7   52
 [4,]   5.9   53
 [5,]   6.6   54
 [6,]   7.3   55
 [7,]   8.1   56
 [8,]   8.8   57
 [9,]  10.6   58
[10,]  12.0   59
[11,]  13.5   60
[12,]  14.9   61
[13,]  16.1   62
[14,]  21.2   63
[15,] 119.0   64
[16,] 124.0   65
[17,] 142.0   66
[18,] 159.0   67
[19,] 182.0   68
[20,] 212.0   69
[21,]  43.0   70
[22,]  24.0   71
[23,]  27.0   72
[24,]  29.0   73


> cov.mve(test.data)
$center
[1] 12.87059 59.23529

$cov
         [,1]     [,2]
[1,] 64.83971 56.85735
[2,] 56.85735 51.44118

$msg
[1] "1 singular samples of size 3 out of 2024"

$crit
[1] 6.218228

$best
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13

$n.obs
[1] 24

```

our implementation `mve` results the best set as the result above, however estimated covariance matrix and critical value differs. any contributions are welcome. @tantei3

**Comment by tantei3** [comment]
@jbytecode I looked at the R source code for the `cov.rob` function and the corresponding C source in the `lqs.c` file, and the implementation looks to be a lot different, as in like they have used `log` and divided the data by `IQR` etc. I couldn't find these operations described in the 2009 Paper mentioned in the Julia docstrings.

If the R implementation is the standard accepted one, then I can port the same to Julia, currently not sure if it is required or not. Would also like to know if there are older Papers with more details and results to compare against.

**Comment by jbytecode** [comment]
Is there any reproducible results in the manuscript? maybe we can try to catch the results given in the paper.

**Comment by tantei3** [comment]
There are two plots: one is based on the philips dataset and other one is pulp fiber dataset (which is supposedly available in the R "robustbase" package. In the review paper though they have mentioned about the MASS implementation in R, so it maybe correct.

**Comment by tantei3** [comment]
Also one more observation I have seen, is that in Julia implementation, it selects `floor((n+p+1)/2)` as the best set, but the rest of the points are returned as outliers (in the phone output, the points from 14-24 for reference), while in the R implementation if we filter out points with higher distance, it returns a smaller subset. 

I wasn't able to get the expected output even in R for the pulp fiber dataset, and the reference review paper is not fully clear to me on the details of implementation yet. My guess is that the R implementation is based on performance improvements which probably is not the simple MVE and hence the original results are not replicated.

**Comment by jbytecode** [comment]
@tantei3 okay I will test our current implementation using some simulated data (a dataset with two distinct clusters in which the first one has more observations). If the algorithm results with the big cluster's covariance matrix, then we accept the current implementation for now.

**Comment by jbytecode** [comment]
@tantei3 `mve()` works well when the `alpha` parameter is tuned, best `h-subset` almost always contains clean observations and any observations that don't belong to this subset are labeled as outliers depending on the `alpha` value which defines the quantile of the ChiSquare distribution with degrees of freedom of `p`.

I am closing this issue for now.
